###
curl -X POST \
  'http://localhost:10000/articles' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
  "Id": "3",
  "Title": "Hello",
  "desc": "Article Description",
  "content": "Article Content"
}'

###
curl -X DELETE \
  'http://localhost:10000/articles/3' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' 

###  
curl -X PUT \
  'http://localhost:10000/articles/1' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
  "Title": "Hello Changed.",
  "desc": "Article Description Changed.",
  "content": "Article Content Changed."
}'